# Generated by Django 5.2.8 on 2025-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scavpost_image_scavpost_latitude_scavpost_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavpost',
            name='taxon_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scavpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scavpost',
            name='image',
            field=models.ImageField(default='http://localhost:8000/media/userPhotos/Colvill_honse.jpg', upload_to='userPhotos/'),
        ),
    ]
